new: upgrade

diff --git a/libexec/mill-new b/libexec/mill-new
--- a/libexec/mill-new
+++ b/libexec/mill-new
@@ -31,12 +31,19 @@ fi
 
 
 # # FUNCTIONS
+
+function create_project()
+{
+    mkdir "$NAME"
+    cd "$NAME"
+}
+
 function get_stationery_from_git()
 {
     TMPDIR="$(mktemp -d /tmp/papermill-new.XXXXXX)" \
     && git clone -q --depth=1 "$STATIONERY_REPO" "$TMPDIR" \
-    && cp -R "$TMPDIR"/"$STATIONERY"/ . \
-    && mv "Document.markdown" ""$NAME".markdown"
+    && cp -R ""$TMPDIR"/"$STATIONERY"/" . \
+    && mv "Document.markdown" "$NAME.markdown"
 }
 
 function setup_config()
@@ -52,26 +59,81 @@ function setup_config()
         ;;
     esac
     
-    touch $file \
-    && echo "# Papermill Config" > $file 
+    # Try to create or update the project config file.
+    touch "$file"
+    
+    # Test if it this failed, bail out if it did.
+    if [[ $? != 0 ]]; then
+        echo "Could not create \"$file\""
+        return 1
+    fi
+    
+    # Now let's fill up this config -- we'll start with a heading and the date.
+    echo "# PAPERMILL PROJECT CONFIGURATION" >> $file
+    echo "# " >> $file
+    echo "# -- started on $(date) -- " >> $file
+    
+    # Lastly, we copy the user config from the line 13 and below to complete the project config.
+    tail -n +13 $_MILL_ROOT/share/mill/user.config >> $file
 }
 
 function start_new_git_repo()
 {
     git init -q \
     && git add --all \
-    && git commit -m "Starting $NAME" |while read REPLY; do echo "    [#] $REPLY"; done \
-    && echo "    [#] SUCCESS!"
+    && git commit -m "Starting $NAME" |while read REPLY; do echo "    [-] $REPLY"; done \
+    && echo "    [#] SUCCESS!" \
+    && echo "[!] If you don't want git, just delete the .git folder."
 }
 
 # # MAIN
 
+# Do all the needed functions in single steps,
+# only continue if the last step did not fail.
+
+# for STEP in \
+#     create_project \
+#     get_stationery_from_git \
+#     setup_config \
+#     start_new_git_repo
+# do
+#     echo "$STEP"
+# done
+
 echo "[>] Creating new "$STATIONERY" in /"$NAME""
-mkdir "$NAME" && cd "$NAME" \
-&& get_stationery_from_git \
-&& setup_config \
-&& start_new_git_repo \
-&& echo "[<] Started new "$STATIONERY" in /"$NAME"" \
-&& echo "[!] If you don't want git, just delete the .git folder." \
-&& mill shim open "." \
-mill shim open ""$NAME".markdown"
+create_project
+if [[ $? != 0 ]]; then
+    echo "    [X] FAIL!"
+    exit 1
+fi
+
+echo "    [#] Getting and unwrapping the stationery."
+get_stationery_from_git
+if [[ $? != 0 ]]; then
+    echo "    [X] FAIL!"
+    exit 1
+fi
+
+echo "    [#] Setting up project config."
+setup_config
+if [[ $? != 0 ]]; then
+    echo "    [X] FAIL!"
+    exit 1
+fi
+
+echo "    [#] Initializing version control."
+start_new_git_repo
+if [[ $? != 0 ]]; then
+    echo "    [X] FAIL!"
+    exit 1
+fi
+
+
+# Since all is well, we try to open the new project folder (in the background).
+mill shim open "." &
+# and the same with the new Markdown file.
+mill shim open "$NAME.markdown" &
+
+echo "[<] Finished creating new $STATIONERY in /$NAME"
+
+exit 0
